
> polymarket-trade-bot-ts@1.0.0 check
> tsx src/inspect.ts log

Market slug: btc-updown-15m-1770018300
Proxy wallet: 0x6031b6eed1c97e853c6e0f03ad3ce3529351f96d

Condition ID: 0x017a65ec1e83fc512fb37d8a1556ae80986b3b4aabbc22f189f637fc7d02721e
Trades found: 135

Time                     Side   Outcom Price      Size       Tx            
---------------------------------------------------------------------------
2026-02-02T07:58:36.000Z BUY    Up     0.9800     19.00      0x1b1da2ae…   
2026-02-02T07:58:28.000Z BUY    Up     0.9700     20.00      0x6da14ce7…   
2026-02-02T07:58:26.000Z BUY    Up     0.9300     10.68      0x1740649d…   
2026-02-02T07:58:14.000Z BUY    Down   0.1000     21.00      0xd8b9b06f…   
2026-02-02T07:58:12.000Z BUY    Down   0.1000     21.00      0x4b18e0aa…   
2026-02-02T07:58:12.000Z BUY    Down   0.1000     21.00      0x52e27538…   
2026-02-02T07:58:12.000Z BUY    Down   0.1000     21.00      0x2e10c854…   
2026-02-02T07:58:04.000Z BUY    Up     0.9500     22.00      0x431f03c8…   
2026-02-02T07:57:58.000Z BUY    Up     0.9300     22.00      0xbb10ac54…   
2026-02-02T07:57:58.000Z BUY    Up     0.9300     22.00      0xf414fb68…   
2026-02-02T07:57:58.000Z BUY    Up     0.9300     22.00      0x81adc0f1…   
2026-02-02T07:57:56.000Z BUY    Up     0.9000     20.60      0x6cefe780…   
2026-02-02T07:57:44.000Z BUY    Down   0.1200     13.91      0x0808eb68…   
2026-02-02T07:57:44.000Z BUY    Down   0.1200     23.00      0x011e508b…   
2026-02-02T07:57:36.000Z BUY    Down   0.1100     23.00      0x92749cd4…   
2026-02-02T07:57:34.000Z BUY    Up     0.9000     23.00      0x2a188abb…   
2026-02-02T07:57:34.000Z BUY    Up     0.8800     9.19       0x2073447b…   
2026-02-02T07:57:34.000Z BUY    Up     0.9000     23.00      0xf4b3c2d6…   
2026-02-02T07:57:32.000Z BUY    Up     0.8400     23.00      0x9436b8da…   
2026-02-02T07:57:32.000Z BUY    Up     0.8400     13.00      0xb0bd3444…   
2026-02-02T07:57:20.000Z BUY    Down   0.0900     24.00      0xa9421ac8…   
2026-02-02T07:57:20.000Z BUY    Down   0.0900     24.00      0xfcafbf2e…   
2026-02-02T07:57:18.000Z BUY    Down   0.0900     24.00      0x74e9c451…   
2026-02-02T07:57:18.000Z BUY    Down   0.0900     24.00      0x9974e687…   
2026-02-02T07:57:06.000Z BUY    Up     0.8200     24.00      0x30aad171…   
2026-02-02T07:57:06.000Z BUY    Up     0.8200     24.00      0xcdfb83d4…   
2026-02-02T07:57:04.000Z BUY    Up     0.8200     24.00      0x1d638571…   
2026-02-02T07:57:04.000Z BUY    Up     0.8200     24.00      0xa8818955…   
2026-02-02T07:57:00.000Z BUY    Down   0.2100     24.00      0x2a29632f…   
2026-02-02T07:56:58.000Z BUY    Down   0.2100     24.00      0xe5c4410f…   
2026-02-02T07:56:58.000Z BUY    Down   0.2100     24.00      0xab37488c…   
2026-02-02T07:56:58.000Z BUY    Down   0.2100     24.00      0x3e1992c3…   
2026-02-02T07:56:50.000Z BUY    Up     0.7800     24.00      0x1ce76ac4…   
2026-02-02T07:56:50.000Z BUY    Up     0.7800     24.00      0xc104fe8c…   
2026-02-02T07:56:50.000Z BUY    Up     0.7800     24.00      0x5fdfc260…   
2026-02-02T07:56:16.000Z BUY    Down   0.1200     24.00      0x2b4d98ff…   
2026-02-02T07:56:14.000Z BUY    Up     0.8800     24.00      0x9660b59a…   
2026-02-02T07:56:14.000Z BUY    Up     0.8800     24.00      0xf0f41b2f…   
2026-02-02T07:56:14.000Z BUY    Up     0.8800     24.00      0x657f849a…   
2026-02-02T07:56:14.000Z BUY    Up     0.8800     24.00      0x3f265ffe…   
2026-02-02T07:56:06.000Z BUY    Down   0.0500     24.00      0x8efd8276…   
2026-02-02T07:56:06.000Z BUY    Down   0.0500     24.00      0x6e505103…   
2026-02-02T07:56:06.000Z BUY    Down   0.0500     24.00      0x4bbb0b7f…   
2026-02-02T07:55:58.000Z BUY    Down   0.0500     24.00      0x9f9318bb…   
2026-02-02T07:55:58.000Z BUY    Down   0.0500     24.00      0x31af13df…   
2026-02-02T07:55:54.000Z BUY    Up     0.9600     24.00      0x5247d6d3…   
2026-02-02T07:55:42.000Z BUY    Down   0.0500     24.00      0x15823559…   
2026-02-02T07:55:22.000Z BUY    Up     0.9400     24.00      0xb6895283…   
2026-02-02T07:55:20.000Z BUY    Up     0.9400     24.00      0xef62f69d…   
2026-02-02T07:55:20.000Z BUY    Up     0.9400     24.00      0xde10cea0…   
2026-02-02T07:55:20.000Z BUY    Up     0.9400     24.00      0xc072a579…   
2026-02-02T07:55:14.000Z BUY    Down   0.0700     13.31      0x0ca9af0c…   
2026-02-02T07:55:10.000Z BUY    Up     0.9400     24.00      0xb9a54b51…   
2026-02-02T07:54:44.000Z BUY    Down   0.0900     24.00      0x0aea6ced…   
2026-02-02T07:54:06.000Z BUY    Down   0.1000     24.00      0x11373704…   
2026-02-02T07:54:06.000Z BUY    Down   0.1000     24.00      0xa93a0a3e…   
2026-02-02T07:54:06.000Z BUY    Down   0.1000     24.00      0x9a39a2f2…   
2026-02-02T07:53:58.000Z BUY    Up     0.9100     24.00      0x78e0d1ab…   
2026-02-02T07:52:54.000Z BUY    Down   0.2100     10.00      0x8fb72eb1…   
2026-02-02T07:52:50.000Z BUY    Up     0.8000     24.00      0xc43aaadd…   
2026-02-02T07:52:50.000Z BUY    Up     0.8000     24.00      0x9660ae13…   
2026-02-02T07:52:38.000Z BUY    Down   0.2400     5.00       0x3a2fbe42…   
2026-02-02T07:52:32.000Z BUY    Down   0.2200     17.00      0xd9a979e1…   
2026-02-02T07:52:30.000Z BUY    Down   0.2200     24.00      0x35815ce2…   
2026-02-02T07:52:30.000Z BUY    Down   0.2200     24.00      0xea2a0933…   
2026-02-02T07:52:30.000Z BUY    Down   0.2200     24.00      0xff672602…   
2026-02-02T07:52:16.000Z BUY    Down   0.2300     5.50       0x03c5065f…   
2026-02-02T07:52:10.000Z BUY    Up     0.7700     24.00      0x619b84d3…   
2026-02-02T07:52:10.000Z BUY    Up     0.7700     23.31      0xeb673f2f…   
2026-02-02T07:52:06.000Z BUY    Down   0.2100     15.00      0x37dd06a5…   
2026-02-02T07:51:50.000Z BUY    Down   0.1800     24.00      0xdf8db187…   
2026-02-02T07:51:50.000Z BUY    Down   0.1800     13.63      0xe8f79bc9…   
2026-02-02T07:51:50.000Z BUY    Down   0.1800     24.00      0xf3311709…   
2026-02-02T07:51:42.000Z BUY    Up     0.7900     24.00      0xb4e3a698…   
2026-02-02T07:51:42.000Z BUY    Up     0.7900     24.00      0x1c13a823…   
2026-02-02T07:51:42.000Z BUY    Up     0.7900     24.00      0xdc358ba7…   
2026-02-02T07:51:26.000Z BUY    Up     0.6700     13.00      0x9fb58dab…   
2026-02-02T07:51:10.000Z BUY    Up     0.6900     12.00      0x02d747d2…   
2026-02-02T07:51:10.000Z BUY    Up     0.6900     24.00      0x62d78435…   
2026-02-02T07:51:08.000Z BUY    Down   0.3237     24.00      0xfbdbfd37…   
2026-02-02T07:51:06.000Z BUY    Up     0.7000     24.00      0xb04e406e…   
2026-02-02T07:51:04.000Z BUY    Up     0.7000     24.00      0x80cfe231…   
2026-02-02T07:51:04.000Z BUY    Up     0.7000     24.00      0x924952d4…   
2026-02-02T07:51:04.000Z BUY    Up     0.7000     24.00      0x5af3c36a…   
2026-02-02T07:51:00.000Z BUY    Up     0.7200     24.00      0x2ff97180…   
2026-02-02T07:50:54.000Z BUY    Down   0.2900     24.00      0xe275d91d…   
2026-02-02T07:50:54.000Z BUY    Down   0.3100     24.00      0x6e4c650d…   
2026-02-02T07:50:54.000Z BUY    Down   0.3100     24.00      0x0f4ab100…   
2026-02-02T07:50:46.000Z BUY    Down   0.2700     24.00      0xb085b329…   
2026-02-02T07:50:34.000Z BUY    Up     0.7400     24.00      0x885fd338…   
2026-02-02T07:50:34.000Z BUY    Up     0.7400     24.00      0xb77f00b6…   
2026-02-02T07:50:34.000Z BUY    Up     0.7400     24.00      0xd82c4a55…   
2026-02-02T07:50:34.000Z BUY    Up     0.7400     24.00      0x36e3cb7c…   
2026-02-02T07:50:32.000Z BUY    Down   0.2900     24.00      0xfbb5de6c…   
2026-02-02T07:50:30.000Z BUY    Down   0.2500     24.00      0xd458ed11…   
2026-02-02T07:50:28.000Z BUY    Down   0.2500     24.00      0xea24bb44…   
2026-02-02T07:50:22.000Z BUY    Up     0.7700     24.00      0xa69321d7…   
2026-02-02T07:50:22.000Z BUY    Up     0.7700     24.00      0x96b69793…   
2026-02-02T07:50:18.000Z BUY    Down   0.2300     24.00      0x383be881…   
2026-02-02T07:50:18.000Z BUY    Down   0.2300     24.00      0x182396dc…   
2026-02-02T07:50:16.000Z BUY    Down   0.2300     24.00      0x0a2d00fe…   
2026-02-02T07:50:16.000Z BUY    Down   0.2300     24.00      0x3760a279…   
2026-02-02T07:50:10.000Z BUY    Up     0.7800     24.00      0x519f31ba…   
2026-02-02T07:49:46.000Z BUY    Down   0.1600     0.39       0x6a6e28fe…   
2026-02-02T07:49:36.000Z BUY    Up     0.8300     24.00      0x0963aba7…   
2026-02-02T07:49:36.000Z BUY    Up     0.8300     3.26       0x8cf43434…   
2026-02-02T07:49:18.000Z BUY    Up     0.8200     24.00      0x38d28997…   
2026-02-02T07:49:16.000Z BUY    Up     0.8200     24.00      0xed55d286…   
2026-02-02T07:49:16.000Z BUY    Up     0.8200     24.00      0xc1004a3e…   
2026-02-02T07:49:16.000Z BUY    Down   0.2000     24.00      0x0ea63a75…   
2026-02-02T07:49:14.000Z BUY    Up     0.7900     20.28      0x2f8c7651…   
2026-02-02T07:49:14.000Z BUY    Down   0.2000     24.00      0x8348a562…   
2026-02-02T07:49:14.000Z BUY    Down   0.2000     24.00      0x86607520…   
2026-02-02T07:49:14.000Z BUY    Down   0.2000     24.00      0xe622cf71…   
2026-02-02T07:49:00.000Z BUY    Up     0.8100     2.00       0x8ba27c84…   
2026-02-02T07:48:56.000Z BUY    Up     0.7800     24.00      0x3e1e7d67…   
2026-02-02T07:48:56.000Z BUY    Up     0.7800     24.00      0x565a7098…   
2026-02-02T07:48:56.000Z BUY    Up     0.7800     24.00      0x32831635…   
2026-02-02T07:48:12.000Z BUY    Down   0.2700     14.50      0x64fc219e…   
2026-02-02T07:47:38.000Z BUY    Down   0.1500     24.00      0x07af5947…   
2026-02-02T07:47:14.000Z BUY    Up     0.7900     24.00      0x9abf35ce…   
2026-02-02T07:47:12.000Z BUY    Up     0.7900     24.00      0x3c7bfb5e…   
2026-02-02T07:46:46.000Z BUY    Up     0.7200     7.20       0x2bffff14…   
2026-02-02T07:46:20.000Z BUY    Down   0.2700     24.00      0x794c133e…   
2026-02-02T07:46:20.000Z BUY    Down   0.2700     24.00      0xe1ea7601…   
2026-02-02T07:46:20.000Z BUY    Down   0.2700     24.00      0x1cc465f1…   
2026-02-02T07:45:32.000Z BUY    Down   0.2800     23.49      0xeb74b02c…   
2026-02-02T07:45:32.000Z BUY    Down   0.2800     24.00      0x65935fff…   
2026-02-02T07:45:30.000Z BUY    Up     0.6800     24.00      0xeb432333…   
2026-02-02T07:45:26.000Z BUY    Up     0.6400     24.00      0x8e8a4c3c…   
2026-02-02T07:45:26.000Z BUY    Up     0.6400     24.00      0x89ab7017…   
2026-02-02T07:45:26.000Z BUY    Up     0.6400     24.00      0xc1f43aa2…   
2026-02-02T07:45:26.000Z BUY    Up     0.6400     24.00      0xa24e1e72…   
2026-02-02T07:45:22.000Z BUY    Down   0.3800     24.00      0x92c27f94…   
2026-02-02T07:45:18.000Z BUY    Down   0.4000     24.00      0x834ae883…   
