
> polymarket-trade-bot-ts@1.0.0 check
> tsx src/inspect.ts log

Market slug: btc-updown-15m-1769924700
Proxy wallet: 0x6031b6eed1c97e853c6e0f03ad3ce3529351f96d

Condition ID: 0xe57a7497dedc737183a6525b3849c7a57f64b8dd79419d39d08b4e10cb075a79
Trades found: 63

Time                     Side   Outcom Price      Size       Tx            
---------------------------------------------------------------------------
2026-02-01T05:59:22.000Z BUY    Up     0.9000     15.00      0xf58d076a…   
2026-02-01T05:59:22.000Z BUY    Up     0.9400     15.00      0x3d07cf8f…   
2026-02-01T05:59:20.000Z BUY    Up     0.9000     15.00      0xd340dcb5…   
2026-02-01T05:59:20.000Z BUY    Up     0.9400     15.00      0x4312819c…   
2026-02-01T05:58:22.000Z BUY    Up     0.7300     20.00      0x00a25162…   
2026-02-01T05:58:22.000Z BUY    Up     0.7300     9.00       0x1de925de…   
2026-02-01T05:58:12.000Z BUY    Down   0.1700     21.00      0x950488d8…   
2026-02-01T05:58:12.000Z BUY    Down   0.1700     21.00      0x96949c4d…   
2026-02-01T05:58:10.000Z BUY    Down   0.1700     21.00      0x837d37c3…   
2026-02-01T05:57:56.000Z BUY    Up     0.7700     11.00      0x41cdd4c2…   
2026-02-01T05:57:46.000Z BUY    Up     0.8200     2.74       0x9d2723f2…   
2026-02-01T05:57:30.000Z BUY    Up     0.8500     24.00      0x252168d5…   
2026-02-01T05:57:20.000Z BUY    Down   0.2317     24.00      0x18a9e56d…   
2026-02-01T05:57:20.000Z BUY    Down   0.2400     24.00      0x67c860ad…   
2026-02-01T05:57:18.000Z BUY    Down   0.2400     24.00      0x881951c5…   
2026-02-01T05:57:18.000Z BUY    Down   0.2400     24.00      0xec9672bd…   
2026-02-01T05:57:10.000Z BUY    Down   0.2200     24.00      0x55869aab…   
2026-02-01T05:55:54.000Z BUY    Down   0.3600     24.00      0x6f2db8dc…   
2026-02-01T05:55:54.000Z BUY    Down   0.3600     9.74       0xcd7fa038…   
2026-02-01T05:55:30.000Z BUY    Down   0.3300     24.00      0x403b9c2f…   
2026-02-01T05:55:28.000Z BUY    Down   0.3400     20.00      0x55338d97…   
2026-02-01T05:55:24.000Z BUY    Down   0.3900     24.00      0x93ac6d53…   
2026-02-01T05:54:42.000Z BUY    Down   0.5000     24.00      0xa29505da…   
2026-02-01T05:52:38.000Z BUY    Down   0.2100     24.00      0x246f1355…   
2026-02-01T05:52:22.000Z BUY    Down   0.3500     24.00      0x3f3b595b…   
2026-02-01T05:52:22.000Z BUY    Down   0.3500     24.00      0x93b489c6…   
2026-02-01T05:52:22.000Z BUY    Down   0.3500     24.00      0x6801a336…   
2026-02-01T05:52:22.000Z BUY    Down   0.3500     24.00      0x8f629a02…   
2026-02-01T05:51:28.000Z BUY    Down   0.5200     24.00      0xc1628aeb…   
2026-02-01T05:51:28.000Z BUY    Down   0.5200     24.00      0x230a499c…   
2026-02-01T05:50:00.000Z BUY    Down   0.5100     24.00      0x0b44aa31…   
2026-02-01T05:50:00.000Z BUY    Down   0.5100     24.00      0x17a351fd…   
2026-02-01T05:49:44.000Z BUY    Up     0.4400     24.00      0x2a0f1f23…   
2026-02-01T05:49:28.000Z BUY    Up     0.5100     24.00      0x350bb611…   
2026-02-01T05:49:24.000Z BUY    Down   0.4500     24.00      0xf6a11084…   
2026-02-01T05:48:40.000Z BUY    Down   0.3000     24.00      0xad9fc175…   
2026-02-01T05:48:38.000Z BUY    Down   0.2900     21.70      0xc58bf86a…   
2026-02-01T05:48:28.000Z BUY    Up     0.6700     24.00      0x36982244…   
2026-02-01T05:48:28.000Z BUY    Up     0.6700     24.00      0xabdd0dd3…   
2026-02-01T05:48:18.000Z BUY    Down   0.3500     24.00      0x37c29ff8…   
2026-02-01T05:48:18.000Z BUY    Down   0.3500     24.00      0xeb1ddbca…   
2026-02-01T05:48:02.000Z BUY    Down   0.3000     24.00      0x3f38fe4f…   
2026-02-01T05:48:02.000Z BUY    Down   0.3000     24.00      0xfa124053…   
2026-02-01T05:48:02.000Z BUY    Down   0.3000     3.86       0xcd71eb66…   
2026-02-01T05:48:02.000Z BUY    Down   0.3000     24.00      0xd36a411a…   
2026-02-01T05:47:48.000Z BUY    Down   0.2900     10.00      0x997cf5b7…   
2026-02-01T05:47:30.000Z BUY    Down   0.3300     5.00       0xb25492e8…   
2026-02-01T05:47:04.000Z BUY    Down   0.2700     24.00      0x45282ddd…   
2026-02-01T05:47:04.000Z BUY    Down   0.2700     24.00      0xaf8eb5f1…   
2026-02-01T05:46:44.000Z BUY    Up     0.6300     24.00      0x58c514bb…   
2026-02-01T05:46:44.000Z BUY    Up     0.6300     24.00      0x4b3d24fa…   
2026-02-01T05:46:22.000Z BUY    Down   0.3500     24.00      0x62b020f0…   
2026-02-01T05:46:20.000Z BUY    Up     0.6400     24.00      0xe4d5e5f3…   
2026-02-01T05:46:16.000Z BUY    Down   0.3600     22.85      0xa3c8fb7e…   
2026-02-01T05:46:10.000Z BUY    Down   0.4000     5.00       0x5f6f9969…   
2026-02-01T05:45:46.000Z BUY    Down   0.3200     24.00      0x319b1dec…   
2026-02-01T05:45:46.000Z BUY    Down   0.3200     23.69      0x5732d150…   
2026-02-01T05:45:36.000Z BUY    Up     0.7000     3.80       0x37564eff…   
2026-02-01T05:45:34.000Z BUY    Down   0.3100     24.00      0x240b7a77…   
2026-02-01T05:45:34.000Z BUY    Down   0.3100     24.00      0x9bdfaf59…   
2026-02-01T05:45:34.000Z BUY    Down   0.3100     24.00      0xfc4b5080…   
2026-02-01T05:45:22.000Z BUY    Down   0.3100     24.00      0x10bb55b1…   
2026-02-01T05:45:22.000Z BUY    Up     0.7000     24.00      0x3f89ebe3…   
