
> polymarket-trade-bot-ts@1.0.0 check
> tsx src/inspect.ts log

Market slug: btc-updown-15m-1769322600
Proxy wallet: 0x6031b6eed1c97e853c6e0f03ad3ce3529351f96d

Condition ID: 0x992d5ca769345bb41dbfc83bc638072e30106c4b183e7b55ae570c0517ed85b3
Trades found: 57

Time                     Side   Outcom Price      Size       Tx            
---------------------------------------------------------------------------
2026-01-25T06:42:24.000Z BUY    Down   0.3300     13.00      0xa2740230…   
2026-01-25T06:41:50.000Z BUY    Up     0.9600     16.00      0xb2c389f8…   
2026-01-25T06:41:50.000Z BUY    Up     0.9600     16.00      0x8fe093b9…   
2026-01-25T06:41:40.000Z BUY    Up     0.5700     16.00      0x683cbaec…   
2026-01-25T06:41:38.000Z BUY    Up     0.6000     16.00      0xbc959875…   
2026-01-25T06:41:32.000Z BUY    Down   0.4144     16.00      0x5e43af6a…   
2026-01-25T06:41:32.000Z BUY    Down   0.3700     10.00      0x4570e37c…   
2026-01-25T06:41:32.000Z BUY    Down   0.4100     16.00      0x0e8eb352…   
2026-01-25T06:41:22.000Z BUY    Down   0.7200     16.00      0x5fcdedf3…   
2026-01-25T06:41:16.000Z BUY    Down   0.7438     16.00      0xed23b127…   
2026-01-25T06:41:16.000Z BUY    Up     0.2500     16.00      0xad7594ff…   
2026-01-25T06:41:14.000Z BUY    Up     0.2406     16.00      0xaea0d38e…   
2026-01-25T06:41:14.000Z BUY    Up     0.2400     16.00      0x0740d86d…   
2026-01-25T06:41:14.000Z BUY    Up     0.2500     16.00      0xf347d3f1…   
2026-01-25T06:39:16.000Z BUY    Down   0.9500     18.00      0x66dd16e0…   
2026-01-25T06:39:16.000Z BUY    Down   0.9500     18.00      0xcc991b3e…   
2026-01-25T06:39:16.000Z BUY    Down   0.9500     18.00      0x1a64d527…   
2026-01-25T06:39:16.000Z BUY    Down   0.9500     18.00      0x917edbd6…   
2026-01-25T06:39:08.000Z BUY    Down   0.9200     14.26      0x8ac7d912…   
2026-01-25T06:39:08.000Z BUY    Down   0.9200     19.00      0x4cfd246e…   
2026-01-25T06:38:44.000Z BUY    Up     0.0900     19.00      0xf3c88ec9…   
2026-01-25T06:38:36.000Z BUY    Down   0.8900     19.00      0xd9251443…   
2026-01-25T06:37:50.000Z BUY    Down   0.8400     8.00       0xa8bea519…   
2026-01-25T06:37:26.000Z BUY    Down   0.7776     19.00      0x8077393d…   
2026-01-25T06:37:24.000Z BUY    Down   0.7700     19.00      0x9cda9075…   
2026-01-25T06:36:58.000Z BUY    Down   0.6900     20.00      0xc96b5f52…   
2026-01-25T06:36:58.000Z BUY    Down   0.6900     20.00      0x1ef1ad8a…   
2026-01-25T06:36:36.000Z BUY    Up     0.3300     20.00      0x878a81f3…   
2026-01-25T06:36:28.000Z BUY    Up     0.2200     20.00      0x1def9d4f…   
2026-01-25T06:36:28.000Z BUY    Up     0.2200     10.35      0xd0604ad8…   
2026-01-25T06:36:22.000Z BUY    Down   0.8000     20.00      0xb090c719…   
2026-01-25T06:36:22.000Z BUY    Down   0.8000     20.00      0x06d46807…   
2026-01-25T06:36:16.000Z BUY    Down   0.7200     20.00      0x9ad10974…   
2026-01-25T06:36:16.000Z BUY    Down   0.7200     20.00      0x4cc2bb77…   
2026-01-25T06:36:14.000Z BUY    Down   0.7170     20.00      0x7cb48f1f…   
2026-01-25T06:35:14.000Z BUY    Up     0.4200     20.00      0xd7c47677…   
2026-01-25T06:35:12.000Z BUY    Up     0.4100     20.00      0x2c99c260…   
2026-01-25T06:35:12.000Z BUY    Up     0.4100     20.00      0xd0a217ae…   
2026-01-25T06:34:44.000Z BUY    Up     0.2900     10.00      0x552647b6…   
2026-01-25T06:34:44.000Z BUY    Up     0.3000     20.00      0x76aaca19…   
2026-01-25T06:34:30.000Z BUY    Down   0.7300     20.00      0x7da96c25…   
2026-01-25T06:34:30.000Z BUY    Down   0.7300     20.00      0x364cb93b…   
2026-01-25T06:34:30.000Z BUY    Down   0.7225     20.00      0x79673f53…   
2026-01-25T06:34:30.000Z BUY    Down   0.7300     20.00      0x592351c9…   
2026-01-25T06:33:48.000Z BUY    Down   0.2300     20.00      0xcb484d2e…   
2026-01-25T06:33:28.000Z BUY    Up     0.5100     20.00      0xcd84adc7…   
2026-01-25T06:33:28.000Z BUY    Up     0.5100     20.00      0xebca2e73…   
2026-01-25T06:32:40.000Z BUY    Up     0.4000     20.00      0x5295d5ec…   
2026-01-25T06:32:32.000Z BUY    Down   0.6000     20.00      0x694d55da…   
2026-01-25T06:31:56.000Z BUY    Up     0.5300     20.00      0xbe28bb92…   
2026-01-25T06:31:56.000Z BUY    Up     0.5300     20.00      0x44c741ba…   
2026-01-25T06:31:36.000Z BUY    Down   0.5200     20.00      0xa476a65f…   
2026-01-25T06:31:34.000Z BUY    Down   0.5200     20.00      0xe48017d4…   
2026-01-25T06:31:32.000Z BUY    Up     0.4600     15.58      0xa43f4d93…   
2026-01-25T06:31:32.000Z BUY    Up     0.4600     20.00      0xe987a566…   
2026-01-25T06:30:56.000Z BUY    Down   0.5000     20.00      0x4eb62928…   
2026-01-25T06:30:54.000Z BUY    Down   0.5000     20.00      0xe6b37229…   
