
> polymarket-trade-bot-ts@1.0.0 check
> tsx src/inspect.ts log

Market slug: eth-updown-15m-1769633100
Proxy wallet: 0x6031b6eed1c97e853c6e0f03ad3ce3529351f96d

Condition ID: 0xe6fba5c2ee6c4a0f856f9258abfe6493098a21ff4ae4f721d9a91e6c2874ecd6
Trades found: 172

Time                     Side   Outcom Price      Size       Tx            
---------------------------------------------------------------------------
2026-01-28T20:59:48.000Z BUY    Up     0.2700     7.00       0xed9ddf50…   
2026-01-28T20:59:48.000Z BUY    Down   0.7800     7.00       0x1a5a6b12…   
2026-01-28T20:59:48.000Z BUY    Down   0.7800     7.00       0xf63e9c4c…   
2026-01-28T20:59:48.000Z BUY    Up     0.2700     7.00       0xb5d27e23…   
2026-01-28T20:57:54.000Z BUY    Down   0.1600     13.00      0x8ba333fb…   
2026-01-28T20:57:54.000Z BUY    Down   0.1600     13.00      0xe2cee476…   
2026-01-28T20:57:52.000Z BUY    Down   0.1600     9.60       0x58036f9a…   
2026-01-28T20:57:50.000Z BUY    Down   0.2400     13.00      0xc44e5b6b…   
2026-01-28T20:57:44.000Z BUY    Up     0.7800     13.00      0x93ad74f2…   
2026-01-28T20:57:44.000Z BUY    Up     0.7800     13.00      0xeaf47e29…   
2026-01-28T20:57:44.000Z BUY    Up     0.7800     13.00      0x87fc06c3…   
2026-01-28T20:57:44.000Z BUY    Up     0.7800     13.00      0xe0508d79…   
2026-01-28T20:57:32.000Z BUY    Up     0.7900     14.00      0x6b4cfd51…   
2026-01-28T20:57:32.000Z BUY    Up     0.7900     14.00      0x8db9cb50…   
2026-01-28T20:57:32.000Z BUY    Up     0.7900     14.00      0x29321982…   
2026-01-28T20:57:20.000Z BUY    Down   0.3500     10.00      0x2abfe4d8…   
2026-01-28T20:57:18.000Z BUY    Up     0.5900     10.00      0x07a0b98b…   
2026-01-28T20:57:18.000Z BUY    Down   0.4400     14.00      0x5d0c017a…   
2026-01-28T20:57:18.000Z BUY    Up     0.6000     14.00      0xecfc60e0…   
2026-01-28T20:57:18.000Z BUY    Down   0.4229     14.00      0x27e025ac…   
2026-01-28T20:57:16.000Z BUY    Down   0.4300     1.00       0x07a7e3ec…   
2026-01-28T20:57:10.000Z BUY    Up     0.6000     14.00      0xdf7505b0…   
2026-01-28T20:57:10.000Z BUY    Up     0.6000     14.00      0xd22ac1a8…   
2026-01-28T20:57:00.000Z BUY    Down   0.4229     14.00      0x126ad53a…   
2026-01-28T20:57:00.000Z BUY    Down   0.4400     2.47       0x9eefabb7…   
2026-01-28T20:56:44.000Z BUY    Down   0.5200     14.00      0x2c9e97ad…   
2026-01-28T20:56:42.000Z BUY    Down   0.5125     14.00      0xb4412cf9…   
2026-01-28T20:56:40.000Z BUY    Up     0.3900     8.06       0xaeccf4ac…   
2026-01-28T20:56:28.000Z BUY    Up     0.3600     4.27       0x08ed22a4…   
2026-01-28T20:56:22.000Z BUY    Up     0.3500     11.06      0x3b8aaf16…   
2026-01-28T20:56:18.000Z BUY    Down   0.6743     14.00      0x1356cd43…   
2026-01-28T20:56:18.000Z BUY    Down   0.6800     14.00      0x0d094244…   
2026-01-28T20:56:16.000Z BUY    Down   0.6476     13.09      0xb762728a…   
2026-01-28T20:55:50.000Z BUY    Up     0.2500     5.00       0x73888df9…   
2026-01-28T20:55:32.000Z BUY    Up     0.3100     14.00      0xf3ffe03f…   
2026-01-28T20:55:30.000Z BUY    Up     0.3100     14.00      0x8fee2ee0…   
2026-01-28T20:55:30.000Z BUY    Up     0.3100     14.00      0xf9a7e5e4…   
2026-01-28T20:55:30.000Z BUY    Up     0.3100     14.00      0x35a672cc…   
2026-01-28T20:55:20.000Z BUY    Up     0.3600     14.00      0xef6c3740…   
2026-01-28T20:55:10.000Z BUY    Down   0.5100     5.00       0xea3b4f97…   
2026-01-28T20:55:06.000Z BUY    Up     0.5200     1.24       0xead27e4a…   
2026-01-28T20:55:00.000Z BUY    Down   0.5900     14.00      0x752e52fb…   
2026-01-28T20:54:50.000Z BUY    Down   0.6600     14.00      0x5be55c13…   
2026-01-28T20:54:50.000Z BUY    Down   0.6600     14.00      0x79bc3276…   
2026-01-28T20:54:50.000Z BUY    Down   0.6600     14.00      0x1d50b082…   
2026-01-28T20:54:46.000Z BUY    Down   0.7000     14.00      0x9c480c6c…   
2026-01-28T20:54:44.000Z BUY    Down   0.7000     14.00      0x4f8380f1…   
2026-01-28T20:54:44.000Z BUY    Down   0.7000     3.63       0x0ce511d5…   
2026-01-28T20:54:38.000Z BUY    Up     0.2500     10.00      0x8da98e61…   
2026-01-28T20:54:16.000Z BUY    Down   0.8000     14.00      0xdb2125ec…   
2026-01-28T20:54:16.000Z BUY    Down   0.8000     14.00      0xb5351772…   
2026-01-28T20:54:16.000Z BUY    Down   0.8000     14.00      0x2c8911fd…   
2026-01-28T20:54:14.000Z BUY    Down   0.8000     14.00      0xb36c11ea…   
2026-01-28T20:54:12.000Z BUY    Up     0.2100     14.00      0xb4ed6a2d…   
2026-01-28T20:54:08.000Z BUY    Up     0.2100     14.00      0x456f48cc…   
2026-01-28T20:54:06.000Z BUY    Up     0.2100     14.00      0x82d55b01…   
2026-01-28T20:54:06.000Z BUY    Up     0.2100     14.00      0x897503ca…   
2026-01-28T20:54:06.000Z BUY    Up     0.2100     14.00      0xccbed85c…   
2026-01-28T20:53:48.000Z BUY    Down   0.7700     14.00      0x081052f4…   
2026-01-28T20:53:48.000Z BUY    Down   0.7500     5.00       0xd5b53d89…   
2026-01-28T20:53:48.000Z BUY    Down   0.7700     14.00      0x1ab01541…   
2026-01-28T20:53:48.000Z BUY    Down   0.7700     14.00      0x6cce23fa…   
2026-01-28T20:53:48.000Z BUY    Down   0.7700     14.00      0x3b9c48d3…   
2026-01-28T20:53:24.000Z BUY    Up     0.2600     14.00      0xd01cebd6…   
2026-01-28T20:53:24.000Z BUY    Up     0.2600     14.00      0x71becde2…   
2026-01-28T20:53:24.000Z BUY    Up     0.2600     14.00      0xced3aab5…   
2026-01-28T20:53:24.000Z BUY    Up     0.2600     14.00      0x2b0a854c…   
2026-01-28T20:53:02.000Z BUY    Up     0.2600     14.00      0xeccedd0c…   
2026-01-28T20:53:02.000Z BUY    Up     0.2600     14.00      0x1c178bac…   
2026-01-28T20:52:52.000Z BUY    Down   0.7400     5.00       0x13cc0332…   
2026-01-28T20:52:50.000Z BUY    Up     0.2500     5.00       0xb4ee5cf8…   
2026-01-28T20:52:44.000Z BUY    Down   0.7400     10.03      0x7f0c0322…   
2026-01-28T20:52:44.000Z BUY    Down   0.7600     3.19       0x37e26fb4…   
2026-01-28T20:52:30.000Z BUY    Up     0.2100     5.00       0x7ebc4464…   
2026-01-28T20:52:20.000Z BUY    Up     0.2400     14.00      0xe2325785…   
2026-01-28T20:52:14.000Z BUY    Down   0.7600     14.00      0x2521ecb3…   
2026-01-28T20:52:14.000Z BUY    Down   0.7600     14.00      0x63a55a5c…   
2026-01-28T20:52:12.000Z BUY    Down   0.7600     14.00      0xfe802c2c…   
2026-01-28T20:52:12.000Z BUY    Down   0.7600     14.00      0xbb2c4e71…   
2026-01-28T20:52:06.000Z BUY    Up     0.2300     7.00       0xda0da304…   
2026-01-28T20:51:56.000Z BUY    Down   0.7500     5.00       0xcaad94f0…   
2026-01-28T20:51:48.000Z BUY    Up     0.2300     4.81       0xcf6a848e…   
2026-01-28T20:51:46.000Z BUY    Up     0.2200     5.00       0x4b421372…   
2026-01-28T20:51:44.000Z BUY    Down   0.7600     5.00       0x86b45161…   
2026-01-28T20:51:38.000Z BUY    Down   0.7500     11.40      0x7b9aadc6…   
2026-01-28T20:51:38.000Z BUY    Down   0.7500     14.00      0xe35f09a2…   
2026-01-28T20:51:36.000Z BUY    Up     0.2500     0.60       0x6cdeefeb…   
2026-01-28T20:51:36.000Z BUY    Up     0.2400     5.49       0x3e7eeea4…   
2026-01-28T20:51:16.000Z BUY    Up     0.2200     14.00      0x287618de…   
2026-01-28T20:51:14.000Z BUY    Up     0.2200     12.00      0x7a2bf828…   
2026-01-28T20:51:08.000Z BUY    Down   0.7800     5.00       0x9af3097d…   
2026-01-28T20:51:00.000Z BUY    Down   0.7700     3.62       0xc6b0a1c3…   
2026-01-28T20:50:44.000Z BUY    Up     0.2500     14.00      0xcba1d767…   
2026-01-28T20:50:44.000Z BUY    Down   0.7800     14.00      0xca8d5a0d…   
2026-01-28T20:50:44.000Z BUY    Down   0.7800     14.00      0xed4b6a8c…   
2026-01-28T20:50:42.000Z BUY    Up     0.2500     14.00      0x4abe83c0…   
2026-01-28T20:50:42.000Z BUY    Up     0.2400     10.00      0x58453fc8…   
2026-01-28T20:50:38.000Z BUY    Up     0.1900     5.00       0xb1378ead…   
2026-01-28T20:50:32.000Z BUY    Up     0.2000     11.00      0xc0f045d4…   
2026-01-28T20:50:24.000Z BUY    Up     0.2500     14.00      0x19ff659b…   
2026-01-28T20:50:24.000Z BUY    Down   0.7600     4.56       0xed1b6cad…   
2026-01-28T20:50:24.000Z BUY    Down   0.7600     14.00      0x9a1ec261…   
2026-01-28T20:50:22.000Z BUY    Up     0.2500     14.00      0x6646fdbf…   
2026-01-28T20:50:22.000Z BUY    Down   0.7600     14.00      0xbc1f8af7…   
2026-01-28T20:50:18.000Z BUY    Up     0.2300     14.00      0xdcaf609c…   
2026-01-28T20:50:14.000Z BUY    Down   0.7800     14.00      0xac7fba6c…   
2026-01-28T20:50:14.000Z BUY    Down   0.7800     14.00      0x68d23322…   
2026-01-28T20:50:12.000Z BUY    Down   0.7800     14.00      0xdf4c1e34…   
2026-01-28T20:50:12.000Z BUY    Down   0.7800     14.00      0x2bd75f78…   
2026-01-28T20:50:10.000Z BUY    Down   0.7700     11.55      0x1545d2ba…   
2026-01-28T20:50:08.000Z BUY    Up     0.2300     14.00      0x0fdcbe44…   
2026-01-28T20:50:08.000Z BUY    Up     0.2200     10.00      0xeaec2195…   
2026-01-28T20:50:06.000Z BUY    Up     0.2200     14.00      0x6ede9723…   
2026-01-28T20:50:06.000Z BUY    Up     0.2200     14.00      0x5654124e…   
2026-01-28T20:50:00.000Z BUY    Up     0.2400     7.00       0x349a77fe…   
2026-01-28T20:49:58.000Z BUY    Up     0.2364     14.00      0x14355a57…   
2026-01-28T20:49:56.000Z BUY    Down   0.7800     14.00      0xc933706d…   
2026-01-28T20:49:56.000Z BUY    Down   0.7800     14.00      0x19807bf9…   
2026-01-28T20:49:56.000Z BUY    Down   0.7800     14.00      0x9af5615b…   
2026-01-28T20:49:44.000Z BUY    Up     0.2400     14.00      0xaa22a517…   
2026-01-28T20:49:34.000Z BUY    Down   0.7000     11.14      0xfeffa414…   
2026-01-28T20:49:30.000Z BUY    Down   0.6241     14.00      0x8c68c34c…   
2026-01-28T20:49:28.000Z BUY    Down   0.5900     0.41       0xbb6a70c7…   
2026-01-28T20:49:28.000Z BUY    Down   0.6000     10.00      0x1cdc78a1…   
2026-01-28T20:49:28.000Z BUY    Down   0.6300     14.00      0xb9aa7eb5…   
2026-01-28T20:49:20.000Z BUY    Down   0.5800     14.00      0xca214514…   
2026-01-28T20:49:18.000Z BUY    Down   0.5600     1.84       0x4a31fdd1…   
2026-01-28T20:49:14.000Z BUY    Down   0.5300     5.00       0x86be4d50…   
2026-01-28T20:49:04.000Z BUY    Up     0.4100     14.00      0x36c6171e…   
2026-01-28T20:48:54.000Z BUY    Down   0.5500     3.98       0x3de986ed…   
2026-01-28T20:48:50.000Z BUY    Down   0.5200     14.00      0x20119bef…   
2026-01-28T20:48:44.000Z BUY    Down   0.5100     10.09      0x54a65083…   
2026-01-28T20:48:36.000Z BUY    Up     0.4900     14.00      0x61b71559…   
2026-01-28T20:48:24.000Z BUY    Down   0.5200     5.00       0xa80bd43e…   
2026-01-28T20:48:14.000Z BUY    Up     0.4700     13.06      0x1e59586a…   
2026-01-28T20:48:12.000Z BUY    Up     0.4600     5.01       0xd66488d2…   
2026-01-28T20:48:06.000Z BUY    Up     0.4600     5.00       0x28a407d2…   
2026-01-28T20:48:00.000Z BUY    Down   0.5100     14.00      0x7cdd3b27…   
2026-01-28T20:48:00.000Z BUY    Down   0.5500     14.00      0x1d5a1064…   
2026-01-28T20:47:54.000Z BUY    Up     0.4900     10.01      0xbd02ee9d…   
2026-01-28T20:47:46.000Z BUY    Down   0.5200     5.00       0x1d97cea4…   
2026-01-28T20:47:38.000Z BUY    Up     0.4300     5.00       0x4d1de025…   
2026-01-28T20:47:38.000Z BUY    Up     0.4500     13.74      0xf66403ba…   
2026-01-28T20:47:18.000Z BUY    Up     0.3900     6.00       0x1b79fc78…   
2026-01-28T20:47:18.000Z BUY    Up     0.3900     14.00      0x9063ff73…   
2026-01-28T20:47:18.000Z BUY    Up     0.4000     10.00      0xb75b5293…   
2026-01-28T20:47:14.000Z BUY    Down   0.6400     14.00      0x94be6205…   
2026-01-28T20:47:14.000Z BUY    Up     0.3761     14.00      0xb13445bd…   
2026-01-28T20:47:12.000Z BUY    Down   0.6450     14.00      0x99d402bf…   
2026-01-28T20:47:12.000Z BUY    Down   0.6000     14.00      0x85dcf54d…   
2026-01-28T20:47:08.000Z BUY    Up     0.4400     5.00       0x78558abc…   
2026-01-28T20:47:06.000Z BUY    Down   0.5500     14.00      0xa25f17c0…   
2026-01-28T20:47:04.000Z BUY    Down   0.5500     14.00      0x0aab8185…   
2026-01-28T20:47:00.000Z BUY    Down   0.5400     5.00       0x119f3fae…   
2026-01-28T20:46:58.000Z BUY    Up     0.4300     14.00      0xe3709b79…   
2026-01-28T20:46:58.000Z BUY    Up     0.4300     0.48       0x87726156…   
2026-01-28T20:46:58.000Z BUY    Up     0.4500     5.00       0x2c2d3cd3…   
2026-01-28T20:46:52.000Z BUY    Up     0.4500     5.00       0xd8aac7a3…   
2026-01-28T20:46:48.000Z BUY    Down   0.5400     14.00      0xc32256b0…   
2026-01-28T20:46:36.000Z BUY    Down   0.4900     14.00      0xad06b4d5…   
2026-01-28T20:46:28.000Z BUY    Up     0.5400     14.00      0x0193a9ec…   
2026-01-28T20:46:24.000Z BUY    Up     0.5200     7.31       0xe68c04bc…   
2026-01-28T20:46:10.000Z BUY    Down   0.4700     5.00       0xe9370a49…   
2026-01-28T20:45:58.000Z BUY    Up     0.5400     14.00      0x4bc5dd79…   
2026-01-28T20:45:56.000Z BUY    Down   0.4700     5.00       0x34c66704…   
2026-01-28T20:45:56.000Z BUY    Down   0.4800     14.00      0x3300d0fe…   
2026-01-28T20:45:56.000Z BUY    Down   0.4800     14.00      0xcd668418…   
2026-01-28T20:45:38.000Z BUY    Up     0.4800     14.00      0xecba4e32…   
2026-01-28T20:45:38.000Z BUY    Up     0.4800     7.09       0x3752b816…   
2026-01-28T20:45:34.000Z BUY    Up     0.5000     14.00      0x8249c1af…   
2026-01-28T20:45:26.000Z BUY    Up     0.4800     5.00       0x906df391…   
2026-01-28T20:45:20.000Z BUY    Down   0.5200     14.00      0x6c547af5…   
