
> polymarket-trade-bot-ts@1.0.0 check
> tsx src/inspect.ts log

Market slug: ethereum-up-or-down-february-2-11pm-et
Proxy wallet: 0x6031b6eed1c97e853c6e0f03ad3ce3529351f96d
Won: Up token

Condition ID: 0x78da14ecccc197ce18fa291d540583a2edcf5f51403e3d9afb40f97dd22e883d
Trades found: 60

Time                     Side   Outcom Price      Size       Tx            
---------------------------------------------------------------------------
2026-02-03T04:59:06.000Z BUY    Up     0.8600     11.00      0xd55755e7…   
2026-02-03T04:59:06.000Z BUY    Up     0.8600     11.00      0xf40cb970…   
2026-02-03T04:58:42.000Z BUY    Down   0.2300     12.00      0x9699576b…   
2026-02-03T04:58:42.000Z BUY    Down   0.2338     12.00      0x4d407b1b…   
2026-02-03T04:58:14.000Z BUY    Down   0.2700     14.00      0xe3b6f844…   
2026-02-03T04:58:14.000Z BUY    Up     0.7400     14.00      0x01cba236…   
2026-02-03T04:58:12.000Z BUY    Down   0.2700     14.00      0xb5e76e76…   
2026-02-03T04:57:54.000Z BUY    Up     0.9000     15.00      0x0e2b2fb7…   
2026-02-03T04:57:54.000Z BUY    Up     0.9000     15.00      0xee8116f2…   
2026-02-03T04:56:36.000Z BUY    Up     0.9700     16.00      0xec1fb9b3…   
2026-02-03T04:56:12.000Z BUY    Up     0.9600     16.00      0x2932de96…   
2026-02-03T04:56:12.000Z BUY    Up     0.9600     16.00      0xf4dd9465…   
2026-02-03T04:56:12.000Z BUY    Up     0.9600     16.00      0xfce8ee71…   
2026-02-03T04:56:10.000Z BUY    Up     0.9600     16.00      0x4f868207…   
2026-02-03T04:56:08.000Z BUY    Up     0.9400     16.00      0x7cf9e015…   
2026-02-03T04:53:32.000Z BUY    Up     0.6400     16.00      0xd8adac4b…   
2026-02-03T04:53:14.000Z BUY    Down   0.4100     16.00      0xc97304c8…   
2026-02-03T04:53:14.000Z BUY    Down   0.4100     0.15       0xac4d0476…   
2026-02-03T04:52:48.000Z BUY    Up     0.7000     16.00      0xa0ae232a…   
2026-02-03T04:50:22.000Z BUY    Up     0.8300     16.00      0x79370a55…   
2026-02-03T04:49:12.000Z BUY    Up     0.8000     16.00      0x5d9150e4…   
2026-02-03T04:49:10.000Z BUY    Up     0.8100     16.00      0xeaeeccff…   
2026-02-03T04:49:10.000Z BUY    Up     0.8000     16.00      0x23c07fd6…   
2026-02-03T04:49:10.000Z BUY    Up     0.8050     16.00      0xe6fcf928…   
2026-02-03T04:48:52.000Z BUY    Down   0.2200     16.00      0x83ab4366…   
2026-02-03T04:48:52.000Z BUY    Down   0.2200     16.00      0x01fc26ad…   
2026-02-03T04:48:50.000Z BUY    Up     0.7800     16.00      0xdfbcf7de…   
2026-02-03T04:46:40.000Z BUY    Up     0.9000     16.00      0xa710215e…   
2026-02-03T04:46:40.000Z BUY    Up     0.9000     16.00      0x2b9c13cb…   
2026-02-03T04:46:40.000Z BUY    Up     0.9000     16.00      0xea62fb47…   
2026-02-03T04:46:40.000Z BUY    Up     0.9000     16.00      0x77726d35…   
2026-02-03T04:46:28.000Z BUY    Up     0.8700     16.00      0xfb3abb3c…   
2026-02-03T04:45:38.000Z BUY    Up     0.9200     16.00      0xe3853ab3…   
2026-02-03T04:42:06.000Z BUY    Up     0.8400     4.00       0x6f7346d9…   
2026-02-03T04:42:06.000Z BUY    Up     0.8400     16.00      0x5fdab097…   
2026-02-03T04:41:06.000Z BUY    Up     0.6700     13.00      0x741b885e…   
2026-02-03T04:40:24.000Z BUY    Down   0.4100     16.00      0x2dccc535…   
2026-02-03T04:40:24.000Z BUY    Down   0.4100     16.00      0x0b05e9fa…   
2026-02-03T04:40:22.000Z BUY    Down   0.4100     16.00      0xf2ec2cd4…   
2026-02-03T04:39:58.000Z BUY    Down   0.4500     16.00      0xc7aeaa57…   
2026-02-03T04:39:58.000Z BUY    Down   0.4500     16.00      0x4d5e7af1…   
2026-02-03T04:39:46.000Z BUY    Up     0.5300     16.00      0x1db9d1ff…   
2026-02-03T04:39:46.000Z BUY    Up     0.5300     16.00      0x6ee39af1…   
2026-02-03T04:39:46.000Z BUY    Up     0.5300     16.00      0x8562b027…   
2026-02-03T04:39:12.000Z BUY    Down   0.5500     8.00       0x2892921a…   
2026-02-03T04:39:12.000Z BUY    Down   0.5500     16.00      0x8806973b…   
2026-02-03T04:39:12.000Z BUY    Down   0.5500     16.00      0x0d2e791c…   
2026-02-03T04:39:00.000Z BUY    Down   0.6000     16.00      0xb074c4b8…   
2026-02-03T04:39:00.000Z BUY    Down   0.6000     16.00      0x4fb68dd1…   
2026-02-03T04:37:42.000Z BUY    Up     0.3300     16.00      0x42485804…   
2026-02-03T04:37:08.000Z BUY    Down   0.6100     16.00      0x0b34715b…   
2026-02-03T04:36:34.000Z BUY    Down   0.6800     16.00      0x896a822b…   
2026-02-03T04:35:10.000Z BUY    Up     0.3000     16.00      0x7837bd0e…   
2026-02-03T04:33:06.000Z BUY    Up     0.2200     3.00       0x257583c5…   
2026-02-03T04:33:04.000Z BUY    Up     0.2200     16.00      0xf398018c…   
2026-02-03T04:33:04.000Z BUY    Up     0.2200     16.00      0xc71e9bae…   
2026-02-03T04:33:02.000Z BUY    Up     0.2000     16.00      0x75b74aa6…   
2026-02-03T04:15:54.000Z BUY    Down   0.4800     16.00      0xe485bd21…   
2026-02-03T04:05:36.000Z BUY    Down   0.6000     16.00      0x2c4ec662…   
2026-02-03T04:03:48.000Z BUY    Down   0.5200     16.00      0x36f3f229…   
