
> polymarket-trade-bot-ts@1.0.0 check
> tsx src/inspect.ts log

Market slug: eth-updown-15m-1769298300
Proxy wallet: 0x6031b6eed1c97e853c6e0f03ad3ce3529351f96d

Condition ID: 0x59fd2323abb0a9d7d5f496fa00bd3ace776596f203bd250b7dd3ed6fbeb8bff0
Trades found: 85

Time                     Side   Outcom Price      Size       Tx            
---------------------------------------------------------------------------
2026-01-24T23:59:00.000Z BUY    Down   0.9700     8.00       0x27c00f4c…   
2026-01-24T23:59:00.000Z BUY    Down   0.9700     8.00       0x3368452e…   
2026-01-24T23:59:00.000Z BUY    Down   0.9700     8.00       0x52ed2035…   
2026-01-24T23:58:48.000Z BUY    Down   0.7925     9.00       0xe22a8e9f…   
2026-01-24T23:58:48.000Z BUY    Down   0.8256     9.00       0x2869b451…   
2026-01-24T23:58:48.000Z BUY    Down   0.8500     0.39       0x79341250…   
2026-01-24T23:58:36.000Z BUY    Up     0.3244     9.00       0xea48fab5…   
2026-01-24T23:58:36.000Z BUY    Up     0.3300     9.00       0xbdaf61c7…   
2026-01-24T23:58:16.000Z BUY    Down   0.6000     9.00       0xded977b9…   
2026-01-24T23:58:12.000Z BUY    Up     0.4500     9.00       0x2e825c05…   
2026-01-24T23:57:48.000Z BUY    Down   0.9200     10.00      0xc3dbef6c…   
2026-01-24T23:57:48.000Z BUY    Down   0.9200     10.00      0xfbe6fe10…   
2026-01-24T23:57:48.000Z BUY    Down   0.9200     10.00      0x43b2abd5…   
2026-01-24T23:57:40.000Z BUY    Up     0.1000     10.00      0x1b60d5a0…   
2026-01-24T23:57:24.000Z BUY    Down   0.7800     10.00      0x85c9ed50…   
2026-01-24T23:57:24.000Z BUY    Down   0.7800     10.00      0xf2a27e5a…   
2026-01-24T23:57:20.000Z BUY    Up     0.1500     10.00      0x9fc806a5…   
2026-01-24T23:56:24.000Z BUY    Down   0.7600     11.00      0xc8a7e960…   
2026-01-24T23:56:24.000Z BUY    Down   0.7600     11.00      0x0f105d69…   
2026-01-24T23:56:22.000Z BUY    Down   0.7600     11.00      0x24cb098a…   
2026-01-24T23:55:30.000Z BUY    Down   0.6900     12.00      0xf46b0441…   
2026-01-24T23:55:30.000Z BUY    Down   0.6900     12.00      0x4bf4a472…   
2026-01-24T23:55:30.000Z BUY    Down   0.6900     12.00      0x4509b086…   
2026-01-24T23:55:30.000Z BUY    Down   0.6900     12.00      0xf8745102…   
2026-01-24T23:55:06.000Z BUY    Down   0.5800     12.00      0xaafe812a…   
2026-01-24T23:55:06.000Z BUY    Down   0.5800     12.00      0x6a3e3fd7…   
2026-01-24T23:55:04.000Z BUY    Up     0.4400     12.00      0x69657e82…   
2026-01-24T23:55:02.000Z BUY    Up     0.4400     12.00      0x8a7813bd…   
2026-01-24T23:54:54.000Z BUY    Down   0.4100     13.00      0xc769657f…   
2026-01-24T23:54:48.000Z BUY    Down   0.3900     13.00      0x541d0dd9…   
2026-01-24T23:54:48.000Z BUY    Down   0.3900     13.00      0xa867806c…   
2026-01-24T23:54:42.000Z BUY    Up     0.6100     7.11       0x6394a81a…   
2026-01-24T23:54:40.000Z BUY    Up     0.6000     12.82      0xcc0388b4…   
2026-01-24T23:54:26.000Z BUY    Down   0.4000     13.00      0x96b7eda9…   
2026-01-24T23:54:26.000Z BUY    Down   0.4000     13.00      0x4a6ef918…   
2026-01-24T23:54:22.000Z BUY    Up     0.6300     13.00      0x495513bc…   
2026-01-24T23:54:22.000Z BUY    Up     0.6300     13.00      0x43812a89…   
2026-01-24T23:54:22.000Z BUY    Up     0.6300     13.00      0x416e9687…   
2026-01-24T23:54:22.000Z BUY    Up     0.6300     13.00      0xfdc9988a…   
2026-01-24T23:53:24.000Z BUY    Up     0.6000     13.00      0x0cf12f32…   
2026-01-24T23:53:22.000Z BUY    Up     0.6000     4.92       0x2c6d4400…   
2026-01-24T23:53:12.000Z BUY    Down   0.4400     13.00      0xb4a08504…   
2026-01-24T23:53:10.000Z BUY    Down   0.4100     13.00      0x9a413928…   
2026-01-24T23:53:10.000Z BUY    Down   0.4000     6.87       0xdc927815…   
2026-01-24T23:52:26.000Z BUY    Up     0.6200     14.00      0xd53b4d65…   
2026-01-24T23:52:26.000Z BUY    Up     0.6200     14.00      0x38471f3e…   
2026-01-24T23:52:26.000Z BUY    Up     0.6200     14.00      0x18a40168…   
2026-01-24T23:52:26.000Z BUY    Up     0.6200     14.00      0x1d4c9394…   
2026-01-24T23:52:06.000Z BUY    Down   0.3200     5.00       0x12dae202…   
2026-01-24T23:52:06.000Z BUY    Down   0.3800     14.00      0x5100e38a…   
2026-01-24T23:52:06.000Z BUY    Down   0.3800     14.00      0x6abedb55…   
2026-01-24T23:51:56.000Z BUY    Up     0.6900     14.00      0x4f729d09…   
2026-01-24T23:51:56.000Z BUY    Up     0.6900     14.00      0xc970a268…   
2026-01-24T23:51:50.000Z BUY    Down   0.3400     14.00      0x348f0d24…   
2026-01-24T23:51:50.000Z BUY    Down   0.3400     14.00      0x8a68408a…   
2026-01-24T23:51:46.000Z BUY    Up     0.6600     14.00      0x6233ce87…   
2026-01-24T23:51:46.000Z BUY    Up     0.6600     13.00      0x5bcf71b9…   
2026-01-24T23:51:40.000Z BUY    Up     0.6500     14.00      0x25854ab8…   
2026-01-24T23:51:40.000Z BUY    Up     0.6500     1.00       0x88c6c4d8…   
2026-01-24T23:50:06.000Z BUY    Down   0.2200     9.00       0xe5eb983c…   
2026-01-24T23:50:04.000Z BUY    Down   0.2300     14.00      0x46d8da1d…   
2026-01-24T23:50:04.000Z BUY    Up     0.7800     14.00      0x68135aa5…   
2026-01-24T23:50:04.000Z BUY    Down   0.2200     14.00      0x401a974b…   
2026-01-24T23:49:58.000Z BUY    Up     0.7700     14.00      0xc206338a…   
2026-01-24T23:49:58.000Z BUY    Up     0.7700     14.00      0xcc853334…   
2026-01-24T23:49:52.000Z BUY    Down   0.1900     11.00      0x6988912a…   
2026-01-24T23:49:40.000Z BUY    Down   0.1900     11.17      0x534b310f…   
2026-01-24T23:49:34.000Z BUY    Up     0.8000     14.00      0xc3c3ac53…   
2026-01-24T23:49:34.000Z BUY    Up     0.8000     14.00      0x34fdff3f…   
2026-01-24T23:49:12.000Z BUY    Up     0.7100     14.00      0xcd7795f6…   
2026-01-24T23:49:08.000Z BUY    Up     0.6850     10.00      0x032666ac…   
2026-01-24T23:48:58.000Z BUY    Up     0.6300     14.00      0x46fc0450…   
2026-01-24T23:48:58.000Z BUY    Up     0.6300     9.71       0x10962975…   
2026-01-24T23:48:06.000Z BUY    Up     0.4800     14.00      0x8083997c…   
2026-01-24T23:47:18.000Z BUY    Up     0.4600     14.00      0x99358ba1…   
2026-01-24T23:47:18.000Z BUY    Up     0.4600     14.00      0xc2c725f2…   
2026-01-24T23:47:08.000Z BUY    Down   0.5500     6.59       0x3fc1de7a…   
2026-01-24T23:47:08.000Z BUY    Down   0.5400     10.59      0xe245f236…   
2026-01-24T23:47:06.000Z BUY    Down   0.4900     8.79       0x68682a31…   
2026-01-24T23:46:20.000Z BUY    Up     0.5043     14.00      0x5c7990a7…   
2026-01-24T23:46:20.000Z BUY    Up     0.5100     14.00      0x1ca60576…   
2026-01-24T23:45:48.000Z BUY    Down   0.4900     14.00      0x3012de18…   
2026-01-24T23:45:46.000Z BUY    Down   0.4900     14.00      0xf281cb3a…   
2026-01-24T23:45:32.000Z BUY    Down   0.4800     14.00      0x58d8f96d…   
2026-01-24T23:45:30.000Z BUY    Down   0.4800     14.00      0x9982aa03…   
