
> polymarket-trade-bot-ts@1.0.0 check
> tsx src/inspect.ts log

Market slug: eth-updown-15m-1770098400
Proxy wallet: 0x6031b6eed1c97e853c6e0f03ad3ce3529351f96d
Won: Down token

Condition ID: 0x8324100527fb778003d2cc095f73918a68531b943de668781339594b8f781883
Trades found: 81

Time                     Side   Outcom Price      Size       Tx            
---------------------------------------------------------------------------
2026-02-03T06:09:06.000Z BUY    Down   0.9600     14.00      0x7d0aa179…   
2026-02-03T06:09:06.000Z BUY    Down   0.9600     14.00      0x03d653dd…   
2026-02-03T06:09:06.000Z BUY    Down   0.9600     14.00      0xb211a8f7…   
2026-02-03T06:08:34.000Z BUY    Down   0.9600     14.00      0x3b9e0e8f…   
2026-02-03T06:08:34.000Z BUY    Down   0.9600     7.45       0x6d5e455d…   
2026-02-03T06:07:52.000Z BUY    Down   0.9700     14.00      0x55f77f9f…   
2026-02-03T06:07:48.000Z BUY    Down   0.9100     10.57      0x3b767221…   
2026-02-03T06:07:46.000Z BUY    Up     0.0800     14.00      0x7f610847…   
2026-02-03T06:07:46.000Z BUY    Down   0.9100     14.00      0xbee978c0…   
2026-02-03T06:07:44.000Z BUY    Up     0.0800     14.00      0xf6cf25dd…   
2026-02-03T06:07:38.000Z BUY    Down   0.9700     14.00      0x6b197f0b…   
2026-02-03T06:07:32.000Z BUY    Up     0.0800     14.00      0x4feb3305…   
2026-02-03T06:07:28.000Z BUY    Down   0.9229     14.00      0xe8705746…   
2026-02-03T06:07:22.000Z BUY    Down   0.9300     14.00      0x19a9a8fc…   
2026-02-03T06:07:22.000Z BUY    Down   0.9200     14.00      0x79da4282…   
2026-02-03T06:07:18.000Z BUY    Down   0.7690     14.00      0xab4d2430…   
2026-02-03T06:07:18.000Z BUY    Down   0.7600     14.00      0x8c13c594…   
2026-02-03T06:07:16.000Z BUY    Up     0.3000     14.00      0x9e24f93e…   
2026-02-03T06:07:16.000Z BUY    Up     0.3000     14.00      0x7154f922…   
2026-02-03T06:07:16.000Z BUY    Down   0.7200     13.97      0x8179f11c…   
2026-02-03T06:07:14.000Z BUY    Up     0.3000     14.00      0x130ce0d4…   
2026-02-03T06:07:08.000Z BUY    Up     0.3100     14.00      0xf79a251d…   
2026-02-03T06:07:08.000Z BUY    Up     0.3100     14.00      0xea231f90…   
2026-02-03T06:07:04.000Z BUY    Down   0.6600     14.00      0x01f8209a…   
2026-02-03T06:07:04.000Z BUY    Down   0.6600     14.00      0xbccf3222…   
2026-02-03T06:07:00.000Z BUY    Up     0.3700     14.00      0x3c470b3a…   
2026-02-03T06:07:00.000Z BUY    Up     0.3700     14.00      0x8b1970dd…   
2026-02-03T06:07:00.000Z BUY    Down   0.6500     14.00      0x2fe29137…   
2026-02-03T06:07:00.000Z BUY    Down   0.6500     14.00      0xce2e034c…   
2026-02-03T06:07:00.000Z BUY    Up     0.3700     14.00      0xe59368a6…   
2026-02-03T06:06:26.000Z BUY    Up     0.4900     14.00      0x8738628f…   
2026-02-03T06:06:26.000Z BUY    Up     0.4900     14.00      0x5cfbaeda…   
2026-02-03T06:06:12.000Z BUY    Up     0.5100     1.79       0xfd065754…   
2026-02-03T06:06:06.000Z BUY    Down   0.5300     14.00      0xe518ae47…   
2026-02-03T06:06:06.000Z BUY    Down   0.5300     14.00      0xb3eb1c52…   
2026-02-03T06:06:02.000Z BUY    Down   0.5700     14.00      0xfba4355d…   
2026-02-03T06:06:02.000Z BUY    Down   0.6000     9.70       0xff1ea5f5…   
2026-02-03T06:05:58.000Z BUY    Down   0.6200     14.00      0x91f19818…   
2026-02-03T06:05:58.000Z BUY    Down   0.6100     10.00      0xc1f4ff03…   
2026-02-03T06:05:46.000Z BUY    Up     0.3800     14.00      0xa0ace28f…   
2026-02-03T06:05:42.000Z BUY    Up     0.4100     14.00      0x41933859…   
2026-02-03T06:05:42.000Z BUY    Up     0.4100     14.00      0xff466a65…   
2026-02-03T06:05:06.000Z BUY    Down   0.4400     14.00      0x3884c689…   
2026-02-03T06:05:06.000Z BUY    Down   0.4400     14.00      0xfc27fc11…   
2026-02-03T06:05:04.000Z BUY    Down   0.3900     2.00       0xeb4d4bc4…   
2026-02-03T06:04:16.000Z BUY    Up     0.6200     14.00      0xf2a46b85…   
2026-02-03T06:04:16.000Z BUY    Up     0.6200     14.00      0x22a851ba…   
2026-02-03T06:04:08.000Z BUY    Up     0.6400     14.00      0xdf5da9b0…   
2026-02-03T06:04:08.000Z BUY    Up     0.6400     3.65       0x7270d187…   
2026-02-03T06:04:02.000Z BUY    Up     0.6800     14.00      0xb67e4d47…   
2026-02-03T06:03:42.000Z BUY    Up     0.7600     5.06       0x9d83a5e8…   
2026-02-03T06:03:42.000Z BUY    Up     0.7600     14.00      0x36f820f6…   
2026-02-03T06:03:42.000Z BUY    Up     0.7600     14.00      0x885e7159…   
2026-02-03T06:03:08.000Z BUY    Down   0.2600     14.00      0x4f4f20e5…   
2026-02-03T06:03:08.000Z BUY    Down   0.2600     14.00      0xc0f33af3…   
2026-02-03T06:03:06.000Z BUY    Down   0.2600     3.00       0xe1b72d89…   
2026-02-03T06:02:52.000Z BUY    Up     0.6500     14.00      0xc8e0f65a…   
2026-02-03T06:02:52.000Z BUY    Up     0.6500     6.09       0x60b58dfa…   
2026-02-03T06:02:42.000Z BUY    Down   0.3600     14.00      0xefaffcdb…   
2026-02-03T06:02:42.000Z BUY    Down   0.3500     10.00      0x287585eb…   
2026-02-03T06:02:36.000Z BUY    Up     0.6300     14.00      0xe14937e6…   
2026-02-03T06:02:22.000Z BUY    Up     0.6200     14.00      0x098ae724…   
2026-02-03T06:01:50.000Z BUY    Down   0.4500     14.00      0x204e8484…   
2026-02-03T06:01:38.000Z BUY    Down   0.3700     14.00      0xfdfec8d4…   
2026-02-03T06:01:38.000Z BUY    Down   0.3200     14.00      0x42d3b589…   
2026-02-03T06:01:38.000Z BUY    Down   0.3400     0.36       0x98d24177…   
2026-02-03T06:01:38.000Z BUY    Down   0.3200     14.00      0xc846ef79…   
2026-02-03T06:01:36.000Z BUY    Down   0.3200     14.00      0xe6dcc7bd…   
2026-02-03T06:01:34.000Z BUY    Up     0.6300     14.00      0x80d9e847…   
2026-02-03T06:00:54.000Z BUY    Down   0.3700     14.00      0xfff9d35d…   
2026-02-03T06:00:40.000Z BUY    Up     0.6500     14.00      0x001e53ba…   
2026-02-03T06:00:40.000Z BUY    Up     0.6500     14.00      0x92a7f891…   
2026-02-03T06:00:40.000Z BUY    Up     0.6500     14.00      0xe37fffcd…   
2026-02-03T06:00:40.000Z BUY    Up     0.6500     14.00      0xda98d6fe…   
2026-02-03T06:00:26.000Z BUY    Down   0.3600     14.00      0x54b14cd3…   
2026-02-03T06:00:26.000Z BUY    Down   0.3600     14.00      0x4c38c71f…   
2026-02-03T06:00:26.000Z BUY    Down   0.3600     14.00      0x67a70163…   
2026-02-03T06:00:24.000Z BUY    Down   0.3600     14.00      0x6e27dc09…   
2026-02-03T06:00:24.000Z BUY    Up     0.6500     14.00      0x9f9a1b0e…   
2026-02-03T06:00:24.000Z BUY    Up     0.6500     14.00      0x13b4bb87…   
2026-02-03T06:00:20.000Z BUY    Up     0.6200     14.00      0x6dd4a862…   
